# Generated by Django 4.1.2 on 2022-10-31 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearID', models.IntegerField()),
                ('pTT_ID', models.IntegerField()),
                ('capture_lat', models.FloatField()),
                ('capture_long', models.FloatField()),
                ('sex', models.TextField()),
                ('age_class', models.TextField()),
                ('ear_applied', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_id', models.IntegerField(default=None)),
                ('recieved', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='bears.bear')),
            ],
        ),
    ]
